# Generated by Django 4.2.1 on 2023-06-09 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import surveys.models.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='shared_surveys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='survey',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=surveys.models.utils.NON_POLYMORPHIC_CASCADE, related_name='questions', to='surveys.survey'),
        ),
        migrations.AddField(
            model_name='fieldanswer',
            name='answer',
            field=models.ForeignKey(on_delete=surveys.models.utils.NON_POLYMORPHIC_CASCADE, related_name='fields', to='surveys.answer'),
        ),
        migrations.AddField(
            model_name='fieldanswer',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='answer',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.survey'),
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MultipleChoicesQuestion',
            fields=[
                ('choicesquestion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='surveys.choicesquestion')),
                ('min_selection', models.IntegerField(blank=True, null=True)),
                ('max_selection', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('surveys.choicesquestion',),
        ),
        migrations.AddField(
            model_name='textanswer',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_answers', to='surveys.openquestion'),
        ),
        migrations.AddField(
            model_name='multiplechoiceanswer',
            name='choices',
            field=models.ManyToManyField(to='surveys.choice'),
        ),
        migrations.AddField(
            model_name='fileanswer',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_answers', to='surveys.filequestion'),
        ),
        migrations.AddField(
            model_name='choiceanswer',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.choice'),
        ),
        migrations.AddField(
            model_name='choiceanswer',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_answers', to='surveys.choicesquestion'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='surveys.choicesquestion'),
        ),
        migrations.AddField(
            model_name='multiplechoiceanswer',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multiple_field_answers', to='surveys.multiplechoicesquestion'),
        ),
    ]
